config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  resources :places, except: [:update, :edit, :destroy]
  root 'places#index'
  get "home/index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
require 'pry'
class Place < ApplicationRecord

  belongs_to :user
  has_and_belongs_to_many :users
  geocoded_by :address
  before_validation :geocode

  def address
    # binding.pry
    [street, city, state, country].compact.reject { |c| c.empty? }.join(', ')
  end

  def location
    [latitude, longitude]
  end

  def set_location(latitude:, longitude:)
    update(latitude: latitude, longitude: longitude)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :places
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
    def after_sign_in_path_for(resource)
      places_path
    end
end

app/controllers/places_controller.rb
require 'pry'
class PlacesController < ApplicationController
  def index
    if current_user.nil?
      redirect_to new_user_session_path
    else
      @places = Place.where(user_id: current_user.id).order('created_at DESC')
      @shared_places = current_user.places
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.user_id = current_user.id
    if @place.geocode && @place.save
      flash[:success] = "Place added!"
      if request.params[:is_public] == "yes"
        User.where.not(id: current_user.id).each do |user|
          @place.users << user
        end
      else
        request.params[:people].each do |user|
          @place.users << User.find(user)
        end
      end
      redirect_to root_path
    else
      flash[:error] = "Address not valid"
      render 'new'
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  private

  def place_params
    params.require(:place).permit(:street, :city, :state, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      .map {
        width: 100%;
        height:400px;
      }
      td {
        padding: 0 0.5em;
        text-align: right;
      }
    </style>
    <title>PlaceSharing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <fieldset class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street, required: :true, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :city, 'City' %>
    <%= f.text_field :city, class: "form-control" %>
  </fieldset>

   <fieldset class="form-group">
    <%= f.label :state, 'State' %>
    <%= f.text_field :state, class: "form-control" %>
  </fieldset>

   <fieldset class="form-group">
    <%= f.label :country, 'Country' %>
    <%= f.text_field :country, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <label> Shared Publicly </label>
    <%= check_box_tag 'is_public', 'yes', true %>
  </fieldset>

  <fieldset class="form-group" style="display:none" id = "share_user">
    <label>Share to</label>
    <%= select_tag "people", options_from_collection_for_select(User.where.not(id: current_user.id), "id", "name", "1"), multiple: true %>
  </fieldset>

  <%= f.submit 'Add!', class: 'btn btn-primary', id: "submit" %>
<% end %>

app/views/places/_place.html.erb
<li>
  <%= link_to place.street, place_path(place) %>
</li>

app/views/places/index.html.erb
<div class="container pt-3">
  <header><h2 lass="display-4">Hi <%= current_user.name %></h2></header>
  <div class= "row">
    <div class="col-sm-6">
      <%= link_to 'Add place', new_place_path, class: 'btn btn-primary' %>
    </div>
    <div class="col-sm-6">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :get) %>
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </div>
  </div>
  <br>
  <% if @places.count > 0 %>
    <strong>Places shared by me:</strong>
    <div class="card">
      <div class="card-block">
        <ul>
          <%= render @places %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if @shared_places.count > 0 %>
    <strong>Places shared by others:</strong>
    <div class="card">
      <div class="card-block">
        <ul>
          <% @shared_places.each do |shared_place| %>
            <li><%= link_to shared_place.street, "/places/#{shared_place.id}" %>
                shared by <%= shared_place.user.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/places/new.html.erb
<div class="container pt-3">
  <header><h1 class="display-4">Add Place</h1></header>

  <%= render 'form' %>
</div>

<script>

    $("#is_public").change(function(){
      if(this.checked)
      {
        $("#share_user").hide();
        $("#submit").show();
      }
      else
      {
        $("#share_user").show();
        $("#submit").hide();
      }
    })

    $("#people").click(function(){
      $("#submit").show();
    })

</script>

app/views/places/show.html.erb
<div class="container pt-3">
  <%= content_tag :div, '', id: 'mycontainer', data: { source: @place } %>
  <div class= "row">
    <div class="col-sm-6">
      <h2><%= @place.street %></h2>
    </div>
    <div class="col-sm-6">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :get) %>
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </div>
  </div>

  <div id="map" class="map">
    <div id="popup" class="ol-popup">
      <a href="#" id="popup-closer" class="ol-popup-closer"></a>
      <div id="popup-content">
      </div>
    </div>
  </div>>

<script>
  data = $('#mycontainer').data('source')
  place = [data.longitude, data.latitude ]
   var attribution = new ol.control.Attribution({
     collapsible: false
 });

 var map = new ol.Map({
     layers: [
         new ol.layer.Tile({
             source: new ol.source.OSM()
         })
     ],
     target: 'map',
     view: new ol.View({
         center: ol.proj.fromLonLat(place),
         maxZoom: 18,
         zoom: 12
     })
 });

  var layer = new ol.layer.Vector({
     source: new ol.source.Vector({
         features: [
             new ol.Feature({
                 geometry: new ol.geom.Point(ol.proj.fromLonLat(place))
             })
         ]
     }),
      style: new ol.style.Style({
            image: new ol.style.Circle({
              radius: 9,
              fill: new ol.style.Fill({color: 'red'})
            })
           })
 });
 map.addLayer(layer);

var container = document.getElementById('popup');
 var content = document.getElementById('popup-content');
 var closer = document.getElementById('popup-closer');

 var overlay = new ol.Overlay({
     element: container,
     autoPan: true,
     autoPanAnimation: {
         duration: 250
     }
 });
 map.addOverlay(overlay);

 closer.onclick = function() {
     overlay.setPosition(undefined);
     closer.blur();
     return false;
 };



</script>